force-app/main/default/objects/User/fields/Allow_Account_and_Contacts_Export__c.field-meta.xml
<CustomField>
    <fullName>Allow_Account_and_Contacts_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow Marketplace members to export Accounts and Contacts in chunk of 500</inlineHelpText>
    <label>Allow Account and Contacts Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Export_Batch_Limit__c.field-meta.xml
<CustomField>
    <fullName>Export_Batch_Limit__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>The default batch limit is set to 10. This count will reset every 30 days</inlineHelpText>
    <label>Export Batch Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Last_Export_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Export_Reset_Date__c</fullName>
    <label>Last Export Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateUsersExportRecordsCount.cls
global class BatchToUpdateUsersExportRecordsCount implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        if(test.isRunningTest())
        {
            return Database.getQueryLocator('SELECT Id,Export_Batch_Limit__c,Last_Export_Reset_Date__c from User where Allow_Account_and_Contacts_Export__c = true');
        }
        String todayDate= Datetime.now().format('yyyy-MM-dd');
        return Database.getQueryLocator('SELECT Id,Export_Batch_Limit__c,Last_Export_Reset_Date__c from User where Allow_Account_and_Contacts_Export__c = true And Last_Export_Reset_Date__c ='+todayDate);
    }
    
    global void execute(Database.BatchableContext bc, List<User> users)
    {
        for(User usr: users)
        {
            usr.Export_Batch_Limit__c = integer.valueof(System.Label.Initial_Export_Batch_Limit);
            usr.Last_Export_Reset_Date__c = Date.Today().addDays(30);
        }
        update users;
    }
    
    global void finish(Database.BatchableContext bc){} 
}