force-app/main/default/objects/User/fields/Allow_Account_and_Contacts_Export__c.field-meta.xml
<CustomField>
    <fullName>Allow_Account_and_Contacts_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow Marketplace members to export Accounts and Contacts in chunk of 500</inlineHelpText>
    <label>Allow Account and Contacts Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Export_Batch_Limit__c.field-meta.xml
<CustomField>
    <fullName>Export_Batch_Limit__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>The default batch limit is set to 10. This count will reset every 30 days</inlineHelpText>
    <label>Export Batch Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Last_Export_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Export_Reset_Date__c</fullName>
    <label>Last Export Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateUsersExportRecordCount_Test.cls
@isTest
public with sharing class BatchToUpdateUsersExportRecordCount_Test {

    @testSetup
    public static void setupTestData() 
    {
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Contact contact = TestDataFactory.createCommunityUserContact();
            User testUser = TestDataFactory.createCommunityUser(contact.Id);
            
            testUser.Allow_Account_and_Contacts_Export__c = true;
            testUser.Last_Export_Reset_Date__c = Date.today().addDays(30);
            update testUser;
        }
    }

    @isTest
    static void testBatchToUpdateUsersExportRecordCount() 
    {     
        // Start the batch job
        Test.startTest();
        BatchToUpdateUsersExportRecordsCount batchInstance = new BatchToUpdateUsersExportRecordsCount();
        Database.executeBatch(batchInstance);
        Test.stopTest();
        
        // Verify that the Export Batch Limit field is updated to 10 for all Users
        List<User> updatedUsers = [SELECT Id, Export_Batch_Limit__c FROM User WHERE Allow_Account_and_Contacts_Export__c = true And UserName='communityuser@testorg.com'];
        for (User usr : updatedUsers) 
        {
            System.assertEquals(10, usr.Export_Batch_Limit__c, 'Export Batch Limit is not be updated');
        }
    }
}