force-app/main/default/objects/User/fields/Is_Community_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Community_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Community User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerOnTaskService.cls
public class TriggerOnTaskService {
    public static void provideAccessToAllUsers(List<Task> newTasks)
    {
        Id taskRecordTypeId = Schema.getGlobalDescribe().get('Task').getDescribe().getRecordTypeInfosByDeveloperName().get('Dakota_360_Task').getRecordTypeId();
        User user = [SELECT is_community_user__c, Contact.AccountId FROM User WHERE id=:UserInfo.getUserId() LIMIT 1];
        for(Task task: newTasks)
        {
            if(task.RecordTypeId == taskRecordTypeId) 
            {
                if(user.is_community_user__c == true && user.Contact !=null && user.Contact.AccountId !=null)
                {   
                    task.IsVisibleInSelfService = true;
                    task.Is_Community_Activity__c = true;
                }
            }
        }
    }
}